name: Deploy to Server

on:
  push:
    branches:
      - main # Runs this workflow when pushing to `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/cargo
            git pull
            pnpm install
            pnpm build

            # Try to restart if exists, otherwise start new PM2 process
            pm2 restart cargo || pm2 start npm --name "cargo" -- start
            pm2 save
