name: Deploy to Server

on:
  push:
    branches:
      - main # Runs this workflow when pushing to `main`

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "connection successful with ip2"
        env:
          ACTIONS_STEP_DEBUG: true
